<script setup lang="ts">
import {
  Cpu,
  MemoryStick,
  Network,
  GripVertical,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  AppWindow,
  AppWindowMac,
  BrainCircuit,
  BrushCleaning,
  Bug,
  ChartPie,
  Check,
  Clock,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  CircleQuestionMark,
  CircleUserRound,
  CodeXml,
  Compass,
  Copy,
  Database,
  Disc3,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  File,
  FileArchive,
  FileAudio,
  FileCode2,
  FileCog,
  FileImage,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileVideo,
  Folder,
  FolderClock,
  FolderOpen,
  FolderPlus,
  FolderX,
  FunnelX,
  Gamepad2,
  Globe2,
  HardDrive,
  History,
  House,
  Info,
  Languages,
  LayoutGrid,
  List,
  LockKeyhole,
  Mail,
  MapPin,
  Minus,
  Monitor,
  Package,
  PackageMinus,
  PackageX,
  Palette,
  Paperclip,
  PanelLeftClose,
  PanelLeftOpen,
  Presentation,
  Power,
  RefreshCw,
  Rocket,
  ScanSearch,
  Search,
  Settings,
  ShieldCheck,
  Square,
  Sparkles,
  SunMoon,
  Trash2,
  Video,
  Wallpaper,
  Wrench,
  X,
  Zap,
} from '@lucide/vue';
import {
  IconLayoutBottombarFilled,
  IconAutomation,
  IconBinary,
  IconBrain,
  IconBrandAndroid,
  IconBrandApple,
  IconBrandArc,
  IconBrandChrome,
  IconBrandCSharp,
  IconBrandDeno,
  IconBrandDocker,
  IconBrandDiscord,
  IconBrandEdge,
  IconBrandFigma,
  IconBrandFirefox,
  IconBrandFlutter,
  IconBrandGolang,
  IconBrandGithubCopilot,
  IconBrandMinecraft,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandOffice,
  IconBrandOpenai,
  IconBrandOpera,
  IconBrandPnpm,
  IconBrandPython,
  IconBrandQq,
  IconBrandReactNative,
  IconBrandRust,
  IconBrandSlack,
  IconBrandSwift,
  IconBrandTeams,
  IconBrandTelegram,
  IconBrandTerraform,
  IconBrandUnity,
  IconBrandVivaldi,
  IconBrandVisualStudio,
  IconBrandVscode,
  IconBrandWhatsapp,
  IconBrandWindows,
  IconBrandYarn,
  IconBrandZoom,
  IconClockCog,
  IconCubeSpark,
  IconDatabaseCog,
  IconFileTime,
  IconLogs,
  IconPackages,
  IconTerminal2,
} from '@tabler/icons-vue';
import {
  siAnaconda,
  siApachemaven,
  siBattledotnet,
  siBlender,
  siBun,
  siClojure,
  siClaudecode,
  siCmake,
  siCocoapods,
  siComposer,
  siDart,
  siDocker,
  siDuckduckgo,
  siEa,
  siElixir,
  siErlang,
  siGimp,
  siGodotengine,
  siGradle,
  siHaskell,
  siHomebrew,
  siHuggingface,
  siJetbrains,
  siJupyter,
  siKeras,
  siLmstudio,
  siModelscope,
  siNeteasecloudmusic,
  siNuget,
  siObsstudio,
  siOllama,
  siPostman,
  siPytorch,
  siRuby,
  siRubygems,
  siSignal,
  siSogou,
  siSpotify,
  siSteam,
  siTensorflow,
  siThunderbird,
  siUnrealengine,
  siUv,
  siVlcmediaplayer,
  siWine,
  siXcode,
  siZig,
  type SimpleIcon,
} from 'simple-icons';
import { computed, type Component } from 'vue';

import MdIcon360Browser from '@/components/icons/md-icon-360-browser.vue';
import MdIconAdobe from '@/components/icons/md-icon-adobe.vue';
import MdIconAiModel from '@/components/icons/md-icon-ai-model.vue';
import MdIconBaiduNetdisk from '@/components/icons/md-icon-baidu-netdisk.vue';
import MdIconBrave from '@/components/icons/md-icon-brave.vue';
import MdIconCarbonChartSunburst from '@/components/icons/md-icon-carbon-chart-sunburst.vue';
import MdIconCarbonChartTreemap from '@/components/icons/md-icon-carbon-chart-treemap.vue';
import MdIconClaude from '@/components/icons/md-icon-claude.vue';
import MdIconDingtalk from '@/components/icons/md-icon-dingtalk.vue';
import MdIconDropbox from '@/components/icons/md-icon-dropbox.vue';
import MdIconElectron from '@/components/icons/md-icon-electron.vue';
import MdIconGithub from '@/components/icons/md-icon-github.vue';
import MdIconGoogle from '@/components/icons/md-icon-google.vue';
import MdIconGitMind from '@/components/icons/md-icon-gitmind.vue';
import MdIconIqiyi from '@/components/icons/md-icon-iqiyi.vue';
import MdIconLark from '@/components/icons/md-icon-lark.vue';
import MdIconLinuxFolder from '@/components/icons/md-icon-linux-folder.vue';
import MdIconProcess from '@/components/icons/md-icon-process.vue';
import MdIconLobsterAi from '@/components/icons/md-icon-lobsterai.vue';
import MdIconManus from '@/components/icons/md-icon-manus.vue';
import MdIconNotion from '@/components/icons/md-icon-notion.vue';
import MdIconQwenWork from '@/components/icons/md-icon-qwen-work.vue';
import MdIconSimpleBrand from '@/components/icons/md-icon-simple-brand.vue';
import MdIconTencentMeeting from '@/components/icons/md-icon-tencent-meeting.vue';
import MdIconTencentVideo from '@/components/icons/md-icon-tencent-video.vue';
import MdIconUtools from '@/components/icons/md-icon-utools.vue';
import MdIconUcBrowser from '@/components/icons/md-icon-uc-browser.vue';
import MdIconWechat from '@/components/icons/md-icon-wechat.vue';
import MdIconWorkBuddy from '@/components/icons/md-icon-workbuddy.vue';
import MdIconWps from '@/components/icons/md-icon-wps.vue';
import MdIconXmind from '@/components/icons/md-icon-xmind.vue';
import MdIconXunlei from '@/components/icons/md-icon-xunlei.vue';
import MdIconYoudaoNote from '@/components/icons/md-icon-youdao-note.vue';
import MdIconYouku from '@/components/icons/md-icon-youku.vue';
import type { IconName } from '@/lib/models/ui';
import { LoggerService } from '@/lib/services/logger-service';

type IconFamily = 'custom' | 'lucide' | 'simpleBrand' | 'tabler';
interface IconDefinition {
  component: Component;
  family: IconFamily;
  path?: string;
}

const props = withDefaults(defineProps<{ name: IconName; size?: number; strokeWidth?: number }>(), {
  size: 20,
  strokeWidth: 1.9,
});

const lucide = (component: Component): IconDefinition => ({ component, family: 'lucide' });
const tabler = (component: Component): IconDefinition => ({ component, family: 'tabler' });
const custom = (component: Component): IconDefinition => ({ component, family: 'custom' });
const simpleBrand = (icon: SimpleIcon): IconDefinition => ({
  component: MdIconSimpleBrand,
  family: 'simpleBrand',
  path: icon.path,
});

const iconMap: Record<IconName, IconDefinition> = {
  sparkles: lucide(Sparkles),
  eye: lucide(Eye),
  eyeOff: lucide(EyeOff),
  rocket: lucide(Rocket),
  wrench: lucide(Wrench),
  brushCleaning: lucide(BrushCleaning),
  chartPie: lucide(ChartPie),
  chartSunburst: custom(MdIconCarbonChartSunburst),
  chartTreemap: custom(MdIconCarbonChartTreemap),
  fileSearch: lucide(FileSearch),
  copy: lucide(Copy),
  clock: lucide(Clock),
  history: lucide(History),
  settings: lucide(Settings),
  hardDrive: lucide(HardDrive),
  cpu: lucide(Cpu),
  memory: lucide(MemoryStick),
  network: lucide(Network),
  grip: lucide(GripVertical),
  chevronDown: lucide(ChevronDown),
  chevronUp: lucide(ChevronUp),
  chevronLeft: lucide(ChevronLeft),
  chevronRight: lucide(ChevronRight),
  panelLeftClose: lucide(PanelLeftClose),
  panelLeftOpen: lucide(PanelLeftOpen),
  refresh: lucide(RefreshCw),
  home: lucide(House),
  search: lucide(Search),
  grid: lucide(LayoutGrid),
  list: lucide(List),
  filterX: lucide(FunnelX),
  folder: lucide(Folder),
  linuxFolder: custom(MdIconLinuxFolder),
  folderOpen: lucide(FolderOpen),
  folderPlus: lucide(FolderPlus),
  file: lucide(File),
  fileText: lucide(FileText),
  fileSpreadsheet: lucide(FileSpreadsheet),
  filePresentation: lucide(Presentation),
  fileArchive: lucide(FileArchive),
  fileAudio: lucide(FileAudio),
  fileVideo: lucide(FileVideo),
  fileImage: lucide(FileImage),
  paperclip: lucide(Paperclip),
  fileCode: lucide(FileCode2),
  fileSettings: lucide(FileCog),
  aiModel: custom(MdIconAiModel),
  package: lucide(Package),
  disc: lucide(Disc3),
  check: lucide(Check),
  minus: lucide(Minus),
  shield: lucide(ShieldCheck),
  lock: lucide(LockKeyhole),
  info: lucide(Info),
  github: lucide(MdIconGithub),
  help: lucide(CircleQuestionMark),
  external: lucide(ExternalLink),
  languages: lucide(Languages),
  theme: lucide(SunMoon),
  palette: lucide(Palette),
  close: lucide(X),
  database: lucide(Database),
  code: lucide(CodeXml),
  brainCircuit: lucide(BrainCircuit),
  application: lucide(AppWindow),
  process: custom(MdIconProcess),
  menuBar: lucide(AppWindowMac),
  taskbar: tabler(IconLayoutBottombarFilled),
  circleUserRound: lucide(CircleUserRound),
  cleanupSystemCache: tabler(IconDatabaseCog),
  cleanupUserCache: lucide(FolderClock),
  cleanupApplicationCache: lucide(LayoutGrid),
  cleanupApplicationLeftovers: lucide(FolderX),
  cleanupBrowserData: lucide(Compass),
  cleanupApplicationOptimization: lucide(PackageMinus),
  cleanupAiModelCache: tabler(IconBrain),
  cleanupDeveloperTools: tabler(IconTerminal2),
  cleanupProjectArtifacts: tabler(IconPackages),
  cleanupContainerCache: tabler(IconBrandDocker),
  cleanupTemporaryFiles: tabler(IconFileTime),
  cleanupStaleCache: tabler(IconClockCog),
  cleanupDiagnosticLogs: tabler(IconLogs),
  cleanupUniversalBinary: tabler(IconBinary),
  cleanupAutomationCache: tabler(IconAutomation),
  cleanupCrashReports: lucide(Bug),
  cleanupLocationCache: lucide(MapPin),
  cleanupPreviewCache: lucide(Eye),
  modelRepository: tabler(IconCubeSpark),
  brand360Browser: custom(MdIcon360Browser),
  brandAdobe: custom(MdIconAdobe),
  brandAndroid: tabler(IconBrandAndroid),
  brandAnaconda: simpleBrand(siAnaconda),
  brandApacheMaven: simpleBrand(siApachemaven),
  brandApple: tabler(IconBrandApple),
  brandArc: tabler(IconBrandArc),
  brandBaiduNetdisk: custom(MdIconBaiduNetdisk),
  brandBattleNet: simpleBrand(siBattledotnet),
  brandBlender: simpleBrand(siBlender),
  brandBrave: custom(MdIconBrave),
  brandBun: simpleBrand(siBun),
  brandCSharp: tabler(IconBrandCSharp),
  brandChrome: tabler(IconBrandChrome),
  brandClaude: custom(MdIconClaude),
  brandClaudeCode: simpleBrand(siClaudecode),
  brandClojure: simpleBrand(siClojure),
  brandCmake: simpleBrand(siCmake),
  brandCocoaPods: simpleBrand(siCocoapods),
  brandComposer: simpleBrand(siComposer),
  brandDingtalk: custom(MdIconDingtalk),
  brandDart: simpleBrand(siDart),
  brandDeno: tabler(IconBrandDeno),
  brandDiscord: tabler(IconBrandDiscord),
  brandDocker: simpleBrand(siDocker),
  brandDropbox: custom(MdIconDropbox),
  brandDuckDuckGo: simpleBrand(siDuckduckgo),
  brandEa: simpleBrand(siEa),
  brandElixir: simpleBrand(siElixir),
  brandErlang: simpleBrand(siErlang),
  brandElectron: custom(MdIconElectron),
  brandEdge: tabler(IconBrandEdge),
  brandFigma: tabler(IconBrandFigma),
  brandFirefox: tabler(IconBrandFirefox),
  brandGimp: simpleBrand(siGimp),
  brandGitMind: custom(MdIconGitMind),
  brandFlutter: tabler(IconBrandFlutter),
  brandGo: tabler(IconBrandGolang),
  brandGoogle: custom(MdIconGoogle),
  brandGithubCopilot: tabler(IconBrandGithubCopilot),
  brandGodot: simpleBrand(siGodotengine),
  brandGradle: simpleBrand(siGradle),
  brandHomebrew: simpleBrand(siHomebrew),
  brandHuggingface: simpleBrand(siHuggingface),
  brandHaskell: simpleBrand(siHaskell),
  brandIqiyi: custom(MdIconIqiyi),
  brandJupyter: simpleBrand(siJupyter),
  brandJetbrains: simpleBrand(siJetbrains),
  brandKeras: simpleBrand(siKeras),
  brandLark: lucide(MdIconLark),
  brandLmStudio: simpleBrand(siLmstudio),
  brandLobsterAi: custom(MdIconLobsterAi),
  brandManus: custom(MdIconManus),
  brandMinecraft: tabler(IconBrandMinecraft),
  brandModelScope: simpleBrand(siModelscope),
  brandNeteaseMusic: simpleBrand(siNeteasecloudmusic),
  brandNodejs: tabler(IconBrandNodejs),
  brandNotion: custom(MdIconNotion),
  brandNpm: tabler(IconBrandNpm),
  brandNuget: simpleBrand(siNuget),
  brandObs: simpleBrand(siObsstudio),
  brandOffice: tabler(IconBrandOffice),
  brandOpenai: tabler(IconBrandOpenai),
  brandOpera: tabler(IconBrandOpera),
  brandOllama: simpleBrand(siOllama),
  brandPnpm: tabler(IconBrandPnpm),
  brandPostman: simpleBrand(siPostman),
  brandPyTorch: simpleBrand(siPytorch),
  brandPython: tabler(IconBrandPython),
  brandQq: tabler(IconBrandQq),
  brandQwenWork: custom(MdIconQwenWork),
  brandReactNative: tabler(IconBrandReactNative),
  brandRust: tabler(IconBrandRust),
  brandRuby: simpleBrand(siRuby),
  brandRubyGems: simpleBrand(siRubygems),
  brandSignal: simpleBrand(siSignal),
  brandSlack: tabler(IconBrandSlack),
  brandSogou: simpleBrand(siSogou),
  brandSpotify: simpleBrand(siSpotify),
  brandSteam: simpleBrand(siSteam),
  brandSwift: tabler(IconBrandSwift),
  brandTensorFlow: simpleBrand(siTensorflow),
  brandTeams: tabler(IconBrandTeams),
  brandTelegram: tabler(IconBrandTelegram),
  brandThunderbird: simpleBrand(siThunderbird),
  brandTencentMeeting: custom(MdIconTencentMeeting),
  brandTencentVideo: custom(MdIconTencentVideo),
  brandTerraform: tabler(IconBrandTerraform),
  brandUnity: tabler(IconBrandUnity),
  brandUnrealEngine: simpleBrand(siUnrealengine),
  brandUv: simpleBrand(siUv),
  brandUcBrowser: custom(MdIconUcBrowser),
  brandUtools: custom(MdIconUtools),
  brandVivaldi: tabler(IconBrandVivaldi),
  brandVisualStudio: tabler(IconBrandVisualStudio),
  brandVlc: simpleBrand(siVlcmediaplayer),
  brandVscode: tabler(IconBrandVscode),
  brandWechat: custom(MdIconWechat),
  brandWorkBuddy: custom(MdIconWorkBuddy),
  brandWine: simpleBrand(siWine),
  brandWhatsapp: tabler(IconBrandWhatsapp),
  brandWindows: tabler(IconBrandWindows),
  brandWps: custom(MdIconWps),
  brandXcode: simpleBrand(siXcode),
  brandXmind: custom(MdIconXmind),
  brandXunlei: custom(MdIconXunlei),
  brandYoudaoNote: custom(MdIconYoudaoNote),
  brandZig: simpleBrand(siZig),
  brandYarn: tabler(IconBrandYarn),
  brandYouku: custom(MdIconYouku),
  brandZoom: tabler(IconBrandZoom),
  windowsApplication: lucide(Monitor),
  uninstall: lucide(PackageX),
  globe: lucide(Globe2),
  download: lucide(Download),
  game: lucide(Gamepad2),
  mail: lucide(Mail),
  scan: lucide(ScanSearch),
  startup: lucide(Power),
  zap: lucide(Zap),
  trash: lucide(Trash2),
  video: lucide(Video),
  wallpaper: lucide(Wallpaper),
  arrowUpDown: lucide(ArrowUpDown),
  arrowUp: lucide(ArrowUp),
  arrowDown: lucide(ArrowDown),
  windowMaximize: lucide(Square),
  windowRestore: lucide(Copy),
};

const icon = computed(() => {
  const definition = (iconMap as Partial<Record<string, IconDefinition>>)[props.name];
  if (definition) return definition;

  // A missing icon must degrade to a visible diagnostic glyph instead of aborting the whole
  // Vue render tree. The stable warning identifies the component contract without user data.
  LoggerService.warn('ui-icon', 'unsupported_icon_name', {
    iconName: typeof props.name === 'string' && props.name ? props.name : 'missing',
  });
  return iconMap.info;
});

// Public icon families expose different render properties. Normalizing them here keeps
// every caller independent from the selected library and keeps brand path data bundled offline.
const rendererProps = computed(() => {
  if (icon.value.family === 'simpleBrand') {
    return { path: icon.value.path };
  }
  if (icon.value.family === 'tabler') return { stroke: props.strokeWidth };
  if (icon.value.family === 'lucide') return { strokeWidth: props.strokeWidth };
  return {};
});
</script>

<template>
  <component :is="icon.component" :size="size" v-bind="rendererProps" aria-hidden="true" />
</template>
